name: boilerplate

on: [push]

jobs:
  # react-redux-typescript-sass-boilerplate/boilerplate
  boilerplate:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [10.x, 12.x, 14.x]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Run Tests
        run: yarn test
      - name: Build
        run: yarn build
      - name: Post Coverage
        uses: codecov/codecov-action@v1
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == '12.x'

    defaults:
      run:
        shell: bash
        working-directory: ./boilerplate

    env:
      CI: true
