name: Node.js CI

on: [push]

jobs:
  default:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn -v
    - run: yarn install
    - run: yarn test
    - run: yarn build

    defaults:
      run:
        shell: bash
        working-directory: ./default

    env:
      CI: true

  container_pattern:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn -v
    - run: yarn install
    - run: yarn test
    - run: yarn build

    defaults:
      run:
        shell: bash
        working-directory: ./presentational-container-pattern

    env:
      CI: true