name: Node.js CI

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_default:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn -v
    - run: yarn install
    - run: yarn test
    - run: yarn build

    defaults:
      run:
        shell: bash
        working-directory: ./default

    env:
      CI: true

  build_container_pattern:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn -v
    - run: yarn install
    - run: yarn test
    - run: yarn build

    defaults:
      run:
        shell: bash
        working-directory: ./presentational-container-pattern

    env:
      CI: true