name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: default
      run: yarn install --frozen-lockfile
      run: yarn build --if-present
      run: yarn test
      working-directory: default
      env:
        CI: true
    - name: presentational-container-pattern
      run: yarn install --frozen-lockfile
      run: yarn build --if-present
      run: yarn test
      working-directory: presentational-container-pattern
      env:
        CI: true
